export default {
    UPDATE_FACEMESH_KEYPOINTS : "UPDATE_FACEMESH_KEYPOINTS",
    UPDATE_POSENET_KEYPOINTS : "UPDATE_POSENET_KEYPOINTS",
    UPDATE_HEAD_ROTATION : "UPDATE_HEAD_ROTATION",
    UPDATE_BODY_ROTATION : "UPDATE_BODY_ROTATION"
}
